Fp 2607 bad styles depending on dependency tree lib react problem detected in fleet
MOV-AI/frontend-npm-lib-react pull request #252
Opened 2023-10-19 19:55 UTC by quirinpa

- [FP-2607](https://movai.atlassian.net/browse/FP-2607): Bad styles depending on dependency tree (lib-react problem) - detected in fleet

2023-10-20 16:50 UTC, manuelnogueiramov requested changes
I don't like the ammount of importants we are adding in this PR.
Also, I don't understand why you added a weird ProfileMenu file.
Keep in mind that we want to remove types altogether from the codebase, I saw some mention of types in this PR. Adding MORE types will not help us remove it. So, let me know what happened here.

2023-10-20 16:50 UTC, manuelnogueiramov commented on src/Components/ProfileMenu/ProfileMenu.js
What the hell is this file!?

2023-10-23 14:30 UTC, quirinpa commented on src/Components/ProfileMenu/ProfileMenu.js
I did not add a dependency on @tty-pt/styles to lib-react.
If I did, it was a mistake.

2023-10-23 14:32 UTC, quirinpa commented on src/Components/ProfileMenu/ProfileMenu.js
That's a compiled file. Has nothing to do with @tty-pt/styles

2023-10-23 14:32 UTC, quirinpa commented on src/Components/ProfileMenu/ProfileMenu.js
Nope. I didn't.

That's a compiled file. It was added by mistake. I'll remove it soon.

2023-10-23 14:34 UTC, quirinpa commented on src/Components/ProfileMenu/ProfileMenu.js
You are wrong about what you're saying. I didn't add types as a dependency.

This file was added by mistake and it does not reference @tty-pt/styles.

2023-10-24 13:00 UTC, quirinpa commented
We did not add types. That is incorrect. Nor styles.

2023-10-24 15:00 UTC, manuelnogueiramov approved these changes

2023-10-24 15:44 UTC, merged