- FP-2810: Fleetboard shows outdated information
MOV-AI/frontend-npm-lib-react pull request #338
Opened 2024-06-12 08:11 UTC by quirinpa

- [FP-2810](https://movai.atlassian.net/browse/FP-2810): Fleetboard shows outdated information

2024-06-12 08:16 UTC, diasdm requested changes
Add a CHANGELOG.md as in https://github.com/MOV-AI/frontend-npm-lib-core/pull/189/files pls

2024-06-12 18:17 UTC, manuelnogueiramov commented
Has this been thoroughly tested? I need to discuss this approach maybe in a pair programming session with @quirinpa to understand what was done here. When are you available @quirinpa ?

2024-06-18 09:16 UTC, quirinpa commented
> Has this been thoroughly tested? I need to discuss this approach maybe in a pair programming session with @quirinpa to understand what was done here. When are you available @quirinpa ?

This was throughly tested. Me and David have verified it together. We've verified that this implementation outperforms what we had previously.

2024-06-18 09:27 UTC, manuelnogueiramov reviewed
Looks better. Still left a few comments. Take a look and let's move forward. Good job.

2024-06-18 09:27 UTC, manuelnogueiramov commented on src/Components/Logs/Logs.js
> +    const newKey = data[j].message + (timestamp * 1000);
If you remove that `* 1000` here and in line **187** what will it impact?

2024-06-18 09:27 UTC, manuelnogueiramov commented on src/Components/Logs/Logs.js
> +            date: date.toLocaleDateString(),
Do we need to convert it to local? Why?

2024-06-18 09:27 UTC, manuelnogueiramov commented on src/Components/Logs/Logs.js
> +            date: date.toLocaleDateString(),
Was it like this before or you're introducing this change now?

2024-06-18 09:37 UTC, quirinpa commented on src/Components/Logs/Logs.js
> +            date: date.toLocaleDateString(),
You see, we were doing something similar before, I only changed where it is. Since we can store it and not do the conversion on every table body render.
The locale time printing uses browser settings to print a format for date and time, it uses standard defaults instead of our custom function, which ends up with the same format in most situations, but does not take the user locale into account.

2024-06-18 09:53 UTC, manuelnogueiramov commented on src/Components/Logs/Logs.js
> +            date: date.toLocaleDateString(),
OK. Was just to confirm that.
Also you can just make a new const and assign the value there and only do the .toLocale computation once.

2024-06-18 09:55 UTC, manuelnogueiramov approved these changes
Good work :tada:

2024-06-18 10:31 UTC, quirinpa commented on src/Components/Logs/Logs.js
> +    const newKey = data[j].message + (timestamp * 1000);
You are right. I removed that multiplication. It doesn't add to the uniqueness of the key or anything else.

2024-06-18 16:04 UTC, diasdm approved these changes

2024-06-19 06:37 UTC, quirinpa commented
Who's the author if we squash?

2024-06-19 08:30 UTC, TiagoLopesQA approved these changes

2024-06-19 08:30 UTC, merged