1.1.5-3 - FP-2858: Removelog duplication for the second overlapping in requests
MOV-AI/frontend-npm-lib-react pull request #340
Opened 2024-06-21 08:07 UTC by quirinpa

- [FP-2858](https://movai.atlassian.net/browse/FP-2858): Removelog duplication for the second overlapping in requests

2024-06-21 09:18 UTC, diasdm requested changes
This implementation seems to rely on backend sending all the logs for the given second and in the same order. But at least the first, we know its not truth :/

2024-06-24 08:26 UTC, quirinpa commented
New implementation should overcome that issue.

2024-06-24 13:29 UTC, manuelnogueiramov commented on package-lock.json
> +      "version": "1.1.5-2",
Why are we changing the package-lock.json, but not the package.json?

2024-06-25 10:50 UTC, quirinpa commented on package-lock.json
> +      "version": "1.1.5-2",
Because I did npm i. And that's the version number on package.json.

2024-06-27 15:10 UTC, diasdm commented
Lets stick to the simpler implementation that does not change the order of logs already presented to the user, so:
* request 1: [a, b, d] 
* request 2: [a, c, d, e]
Should result in the following being presented to the user:
* render 1: [a, b, d] 
* render 2:  [a, b, d, c, e]

2024-06-27 15:12 UTC, quirinpa commented
I think you mean "that does not insert logs between those the user already seen".
Because the order of the logs is currently preserved, but will not after we make that change.
That said, will do.

2024-06-27 16:23 UTC, manuelnogueiramov submitted a review, later dismissed
Just a small non-blocking comment. 
Code still looks confusing, but the comments help :+1:

2024-06-27 16:23 UTC, manuelnogueiramov commented on src/Components/Logs/Logs.js
> +  );
do we need the empty array here?

Would this work all the same?

```suggestion
  return data.slice(0, z).map(log => transformLog(log)).concat(
    Object.values(map).sort(({ index: a }, { index: b }) => a - b),
    oldLogs.slice(i),
  );
```

2024-06-28 08:24 UTC, quirinpa commented on src/Components/Logs/Logs.js
> +  );
I think it would still work, yes. Should I change it?

2024-06-28 10:49 UTC, manuelnogueiramov commented on src/Components/Logs/Logs.js
> +  );
Yeah. Test it before shipping tho! Good job.

2024-06-28 16:10 UTC, diasdm commented
The last few commits:
- Simplify the log de-duplication algorithm
- Move the logs transformation outside the de-duplication
- Fix a bug where the current time was being used to fetch data (which in edge cases made a request for the second before the the timestamp of last log)

2024-07-02 11:14 UTC, manuelnogueiramov approved these changes
Good job. If @diasdm is happy, I'm happy :smile:

2024-07-02 11:28 UTC, quirinpa commented on src/Components/Logs/Logs.js
> +// import useUpdateEffect from "./hooks/useUpdateEffect";
Nope. Rmoved

2024-07-02 12:13 UTC, manuelnogueiramov commented on src/Components/Logs/Logs.js
> -    clearLogs();
Are we sure this is no longer needed?

2024-07-02 12:13 UTC, manuelnogueiramov submitted a review, later dismissed

2024-07-02 12:40 UTC, quirinpa commented on src/Components/Logs/Logs.js
> -    clearLogs();
Yes. The useEffect thing does the job.

2024-07-02 13:28 UTC, diasdm approved these changes

2024-07-02 14:28 UTC, merged